parameters:
    leapt_core.paginator.template: ~

services:
    # Form types
    leapt_core.file_type:
        class: Leapt\CoreBundle\Form\Type\FileType
        tags:
            - { name: form.type }
        calls:
            - [ setUploadDir, [ "%leapt_core.upload_dir%" ] ]

    # Form type extensions
    leapt_core.collection_type_extension:
        class: Leapt\CoreBundle\Form\Extension\CollectionTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\CollectionType }

    # Field entity event subscriber
    leapt_core.file_subscriber:
        class: Leapt\CoreBundle\Listener\FileSubscriber
        arguments: [ '@leapt_core.file_storage.manager' ]
        tags:
            - { name: doctrine.event_subscriber }

    # Navigation
    leapt_core.navigation:
        class: Leapt\CoreBundle\Navigation\NavigationRegistry
        arguments: [ "@request_stack" ]

    leapt_core.twig_navigation:
        class: Leapt\CoreBundle\Twig\Extension\NavigationExtension
        arguments: [ "@leapt_core.navigation" ]
        tags:
            - { name: twig.extension }

    # Twig extensions
    leapt_core.twig_gravatar:
        class: Leapt\CoreBundle\Twig\Extension\GravatarExtension
        tags:
            - { name: twig.extension }

    leapt_core.twig_date:
        class: Leapt\CoreBundle\Twig\Extension\DateExtension
        arguments: [ "@translator" ]
        tags:
            - { name: twig.extension }

    leapt_core.twig_text:
        class: Leapt\CoreBundle\Twig\Extension\TextExtension
        tags:
            - { name: twig.extension }

    leapt_core.twig_google:
        class: Leapt\CoreBundle\Twig\Extension\GoogleExtension
        arguments: [ "%leapt_core.google_analytics.tracking_id%", "%leapt_core.google_analytics.debug%" ]
        calls:
            - [ setDomainName, [ "%leapt_core.google_analytics.domain_name%" ]]
            - [ setAllowLinker, [ "%leapt_core.google_analytics.allow_linker%" ]]
            - [ setTagsManagerId, [ "%leapt_core.google_tags_manager.id%" ]]
        tags:
            - { name: twig.extension }

    leapt_core.twig_facebook:
        class: Leapt\CoreBundle\Twig\Extension\FacebookExtension
        arguments: [ "%leapt_core.facebook.app_id%" ]
        tags:
            - { name: twig.extension }

    leapt_core.twig_site:
        class: Leapt\CoreBundle\Twig\Extension\SiteExtension
        tags:
            - { name: twig.extension }

    leapt_core.twig_paginator:
        class: Leapt\CoreBundle\Twig\Extension\PaginatorExtension
        arguments: [ "%leapt_core.paginator.template%", "@request_stack" ]
        tags:
            - { name: twig.extension }

    Leapt\CoreBundle\Twig\Extension\DatalistExtension:
        arguments: [ '@request_stack' ]
        tags:
            - { name: twig.extension }

    # RSS feeds
    leapt_core.feed_manager:
        class: Leapt\CoreBundle\Feed\FeedManager
        public: true

    leapt_core.request_listener:
        class: Leapt\CoreBundle\Listener\RequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    # Google sitemap
    leapt_core.sitemap_manager:
        class: Leapt\CoreBundle\Sitemap\SitemapManager
        arguments: [ "@validator" ]
        public: true

    # Recaptcha
    Leapt\CoreBundle\Locale\LocaleResolver:
        public: false
        arguments:
            - '%leapt_core.recaptcha.locale_key%'
            - '%leapt_core.recaptcha.locale_from_request%'
            - '@request_stack'

    Leapt\CoreBundle\Form\Type\RecaptchaType:
        arguments:
            - '%leapt_core.recaptcha.public_key%'
            - '%leapt_core.recaptcha.enabled%'
            - '%leapt_core.recaptcha.ajax%'
            - '@Leapt\CoreBundle\Locale\LocaleResolver'
            - '%leapt_core.recaptcha.api_host%'
        tags:
            - { name: form.type }

    Leapt\CoreBundle\Form\Type\RecaptchaV3Type:
        arguments:
            - '%leapt_core.recaptcha.public_key%'
            - '%leapt_core.recaptcha.enabled%'
            - '%leapt_core.recaptcha.hide_badge%'
            - '%leapt_core.recaptcha.api_host%'
        tags:
            - { name: form.type }

    Leapt\CoreBundle\Validator\Constraints\RecaptchaValidator:
        arguments:
            - '%leapt_core.recaptcha.enabled%'
            - '%leapt_core.recaptcha.private_key%'
            - '@request_stack'
            - '%leapt_core.recaptcha.http_proxy%'
            - '%leapt_core.recaptcha.verify_host%'
        tags:
            - { name: validator.constraint_validator, alias: 'leapt_core.recaptcha' }

    Leapt\CoreBundle\Validator\Constraints\RecaptchaV3Validator:
        arguments:
            - '%leapt_core.recaptcha.enabled%'
            - '%leapt_core.recaptcha.private_key%'
            - '%leapt_core.recaptcha.score_threshold%'
            - '@request_stack'
            - '@logger'
        tags:
            - { name: validator.constraint_validator, alias: 'leapt_core.recaptcha_v3' }

    Leapt\CoreBundle\Datalist\DatalistFactory:
        $formFactory: '@form.factory'
        $router: '@router'

    Leapt\CoreBundle\Controller\FeedController:
        arguments: [ '@leapt_core.feed_manager', '@validator', '@twig' ]
        public: true

    Leapt\CoreBundle\Controller\SitemapController:
        arguments: [ '@leapt_core.sitemap_manager', '@router.default', '@twig', '@http_kernel' ]
        public: true

    leapt_core.file_storage.filesystem:
        class: Leapt\CoreBundle\FileStorage\FilesystemStorage
        arguments: [ "%leapt_core.upload_dir%" ]

    leapt_core.file_storage.flysystem:
        class: Leapt\CoreBundle\FileStorage\FlysystemStorage
        arguments: [ [] ]

    leapt_core.file_storage.manager:
        class: Leapt\CoreBundle\FileStorage\FileStorageManager
        arguments: [ '@leapt_core.file_storage.filesystem', '@leapt_core.file_storage.flysystem' ]
