name: Build docs

on:
  push:
    branches: ['6.x']
    tags: ['v*']
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/build-docs.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.x

      - name: Install mkdocs-material
        run: pip install mkdocs-material


      - name: Deploy documentation
        run: mkdocs gh-deploy --force
