name: Build docs

on:
  push:
    branches: ['6.x']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.x

      - name: Install mkdocs-material
        run: pip install mkdocs-material


      - name: Deploy documentation
        run: mkdocs gh-deploy --force
