name: Build docs

on:
  push:
    branches: ['6.x']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: 3.x

      - name: Install mkdocs-material
        run: pip install mkdocs-material


      - name: Deploy documentation
        run: mkdocs gh-deploy --force
