name: Coding Standards

on:
  pull_request:
    branches: ['5.x', '4.x', '3.x']
  push:
    branches: ['5.x', '4.x', '3.x']

jobs:
  easy-coding-standard:
    name: Easy Coding Standard (PHP ${{ matrix.php-version }})
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        php-version:
          - '8.4'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}
          tools: cs2pr

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run Easy Coding Standard
        run: 'vendor/bin/ecs --output-format=checkstyle | cs2pr'
