name: Coding Standards

on:
  pull_request:
    branches: ["*.x"]
  push:
    branches: ["*.x"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  easy-coding-standard:
    name: Easy Coding Standard (PHP ${{ matrix.php-version }})
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        php-version:
          - '8.5'

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}

      - name: Install Composer dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0

      - name: Run Easy Coding Standard
        run: vendor/bin/ecs
