name: Coding Standards

on:
  pull_request:
    branches: ["*.x"]
  push:
    branches: ["*.x"]

jobs:
  easy-coding-standard:
    name: Easy Coding Standard (PHP ${{ matrix.php-version }})
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        php-version:
          - '8.5'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}
          tools: cs2pr

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run Easy Coding Standard
        run: 'vendor/bin/ecs --output-format=checkstyle | cs2pr'
