name: Continuous Integration

on:
  pull_request:
    branches: ["*.x"]
  push:
    branches: ["*.x"]

jobs:
  phpunit:
    name: PHPUnit (PHP ${{ matrix.php-version }} - Symfony ${{ matrix.symfony-version }})
    runs-on: ubuntu-24.04
    continue-on-error: ${{ matrix.continue-on-error || false }}
    env:
      SYMFONY_REQUIRE: ${{ matrix.symfony-version }}

    strategy:
      matrix:
        php-version:
          - '8.4'
          - '8.5'
        symfony-version:
          - '7.4.*'
          - '8.0.*'
        include:
          - php-version: '8.5'
            symfony-version: '8.1.*@dev'
            continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Install PHP with pcov
        uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
          php-version: ${{ matrix.php-version }}
          extensions: pdo_sqlite
          tools: flex

      - name: Configure Composer minimum-stability for dev versions
        if: contains(matrix.symfony-version, 'dev')
        run: composer config minimum-stability dev

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run PHPUnit
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        if: matrix.php-version == '8.4' && matrix.symfony-version == '7.4.*'
