name: Continuous Integration

on:
  pull_request:
    branches: ["*.x"]
  push:
    branches: ["*.x"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  phpunit:
    name: PHPUnit (PHP ${{ matrix.php-version }} - Symfony ${{ matrix.symfony-version }})
    runs-on: ubuntu-24.04
    continue-on-error: ${{ matrix.continue-on-error || false }}
    env:
      SYMFONY_REQUIRE: ${{ matrix.symfony-version }}

    strategy:
      matrix:
        php-version:
          - '8.4'
          - '8.5'
        symfony-version:
          - '7.4.*'
          - '8.0.*'
        include:
          - php-version: '8.5'
            symfony-version: '8.1.*@dev'
            continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 2

      - name: Install PHP with pcov
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
        with:
          coverage: pcov
          php-version: ${{ matrix.php-version }}
          extensions: pdo_sqlite
          tools: flex

      - name: Configure Composer minimum-stability for dev versions
        if: contains(matrix.symfony-version, 'dev')
        run: composer config minimum-stability dev

      - name: Install Composer dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0

      - name: Run PHPUnit
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
        if: matrix.php-version == '8.4' && matrix.symfony-version == '7.4.*'
